model:
  base_learning_rate: 1e-3
  target: classification.modules.base.MLPclassifica
  params:
    num_classes: 2
    data_key: ppi_data
    in_channels: 64
    dropout: 0.2
    weight_decay: 1e-4
    over_sampling: None


dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 32
        num_workers: 0
        train:
            target: classification.dataloader.ppi.PPITrain
            params:
              ppi_data: ./data/human/train_balance_vote5.csv
              essential_data: ./data/human/deg_dna_with_feature.csv
              nonessential_data: ./data/human/ccds_nonan_data_with_feature.csv
              embedding_data: ./data/human/or_ppi_64/1000-emebdding.npy

        validation:
            target: classification.dataloader.ppi.PPIEval
            params:
              ppi_data: ./data/human/eval_balance_vote5.csv
              essential_data: ./data/human/deg_dna_with_feature.csv
              nonessential_data: ./data/human/ccds_nonan_data_with_feature.csv
              embedding_data: ./data/human/or_ppi_64/1000-emebdding.npy

