model:
  base_learning_rate: 1e-3
  target: classification.modules.base.MLPclassifica
  params:
    num_classes: 2
    data_key: dna_data
    in_channels: 4545
    dropout: 0.2
    weight_decay: 1e-4
    over_sampling: None

    loss:
      target: torch.nn.CrossEntropyLoss

dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 32
        num_workers: 0
        train:
            target: classification.dataloader.dna.DNATrain
            params:
              label_path: ./data/human/train_vote5.csv
              essential_data: ./data/human/deg_dna_with_feature.csv
              nonessential_data: ./data/human/ccds_nonan_data_with_feature.csv

        validation:
            target: classification.dataloader.dna.DNAEval
            params:
              label_path: ./data/human/eval_vote5.csv
              essential_data: ./data/human/deg_dna_with_feature.csv
              nonessential_data: ./data/human/ccds_nonan_data_with_feature.csv

