model:
  base_learning_rate: 1e-4
  target: classification.modules.base.MLPclassifica
  params:
    over_sampling: SOMTE
    num_classes: 2
    data_key: ppi_data
    in_channels: 128
    dropout: 0.2
    weight_decay: 1e-4
    loss:
      target: torch.nn.CrossEntropyLoss


dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 128
        num_workers: 0
        train:
            target: classification.dataloader.ppi.PPITrain
            params:
              ppi_data: ./data/and/train.csv
              essential_data: ./data/and/essential.csv
              nonessential_data: ./data/and/nonessential.csv
              embedding_data: ./data/and/0005-emebdding.npy

        validation:
            target: classification.dataloader.ppi.PPIEval
            params:
              ppi_data: ./data/and/eval.csv
              essential_data: ./data/and/essential.csv
              nonessential_data: ./data/and/nonessential.csv
              embedding_data: ./data/and/0005-emebdding.npy

