model:
  base_learning_rate: 1e-3
  target: classification.modules.base.DoubleHeadMLPclassifica
  params:
    num_classes: 2
    data_key: ppi_data
    dna_in_channels: 64
    dna_out_channels: 64
    ppi_in_channels: 64
    ppi_out_channels: 64
    dropout: 0.2
    weight_decay: 1e-4
    over_sampling: None


dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 32
        num_workers: 0
        train:
            target: classification.dataloader.dna_ppi.DNA_PPITrain
            params:
              label_path: ./data/human/train_vote5.csv
              essential_data: ./data/human/deg_nonan_data_with_pca64feature.csv
              nonessential_data: ./data/human/ccds_nonan_data_with_pca64feature.csv
              embedding_data: ./data/human/or_ppi_64/1000-emebdding.npy
              features: 64

        validation:
            target: classification.dataloader.dna_ppi.DNA_PPIEval
            params:
              label_path: ./data/human/eval_vote5.csv
              essential_data: ./data/human/deg_nonan_data_with_pca64feature.csv
              nonessential_data: ./data/human/ccds_nonan_data_with_pca64feature.csv
              embedding_data: ./data/human/or_ppi_64/1000-emebdding.npy
              features: 64

